// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJVKNK7c2wYoGpThkPRR4AV1PcUXmnvc',
    appId: '1:336164230355:web:6d636417b21c708d303026',
    messagingSenderId: '336164230355',
    projectId: 'thecarveout-ce0f3',
    authDomain: 'thecarveout-ce0f3.firebaseapp.com',
    databaseURL: 'https://thecarveout-ce0f3-default-rtdb.firebaseio.com',
    storageBucket: 'thecarveout-ce0f3.firebasestorage.app',
    measurementId: 'G-JLTZXZF131',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuqtLrjVx-fE1Wo3SxTikB85cVV037Ng',
    appId: '1:336164230355:android:b092b15f8ad74058303026',
    messagingSenderId: '336164230355',
    projectId: 'thecarveout-ce0f3',
    databaseURL: 'https://thecarveout-ce0f3-default-rtdb.firebaseio.com',
    storageBucket: 'thecarveout-ce0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOarGTD9LuRlUHFJDTE11qgXLBxAZai-s',
    appId: '1:336164230355:ios:3e798756d0645506303026',
    messagingSenderId: '336164230355',
    projectId: 'thecarveout-ce0f3',
    databaseURL: 'https://thecarveout-ce0f3-default-rtdb.firebaseio.com',
    storageBucket: 'thecarveout-ce0f3.firebasestorage.app',
    iosBundleId: 'com.example.congressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOarGTD9LuRlUHFJDTE11qgXLBxAZai-s',
    appId: '1:336164230355:ios:3e798756d0645506303026',
    messagingSenderId: '336164230355',
    projectId: 'thecarveout-ce0f3',
    databaseURL: 'https://thecarveout-ce0f3-default-rtdb.firebaseio.com',
    storageBucket: 'thecarveout-ce0f3.firebasestorage.app',
    iosBundleId: 'com.example.congressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlJVKNK7c2wYoGpThkPRR4AV1PcUXmnvc',
    appId: '1:336164230355:web:d763c507e62ebfef303026',
    messagingSenderId: '336164230355',
    projectId: 'thecarveout-ce0f3',
    authDomain: 'thecarveout-ce0f3.firebaseapp.com',
    databaseURL: 'https://thecarveout-ce0f3-default-rtdb.firebaseio.com',
    storageBucket: 'thecarveout-ce0f3.firebasestorage.app',
    measurementId: 'G-4HGJGKJSQQ',
  );
}
