import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'pages/front_page.dart'; // Custom widget that shows blog data
import 'firebase_options.dart'; // Auto-generated by Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'The Carveout',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: FrontPage(),
      debugShowCheckedModeBanner: false,
    );
  }
}
